Repository himsumzzin/my-buddy-hero, pull requests merged in 2022-12, with the labels that each got.

#26 feat: Add figma design global css theme file
  src/styles/theme.css
Labels: 채와와 🐵, 기능 구현

#29 feat: Implement Link Component
  .storybook/main.js
  src/components/Link/Link.module.css
  src/components/Link/Link.stories.tsx
  src/components/Link/Link.tsx
  src/styles/custom-base.css
  src/styles/globals.css
Labels: 재영 🦄, 기능 구현, 버그, 환경구성

#31 config: postCSS 환경 구성
  .vscode/settings.json
Labels: 재영 🦄, 환경구성

#32 [feat] 버튼 컴포넌트 구현
  src/components/common/Button/Button.module.css
  src/components/common/Button/Button.stories.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Button/index.js
  src/components/common/index.js
  src/styles/custom-base.css
  src/styles/theme.css
Labels: 채와와 🐵, 기능 구현

#33 [feat] Link컴포넌트 기능 추가
  .vscode/settings.json
  src/components/Link/Link.module.css
  src/components/Link/Link.stories.tsx
  src/components/Link/Link.tsx
Labels: 재영 🦄, 기능 구현

#44 feat: Add Button component XS size
  src/components/common/Button/Button.module.css
  src/components/common/Button/Button.stories.tsx
  src/components/common/Button/Button.tsx
Labels: 기능 구현

#50 [fix] 로그인, 회원가입 페이지 구현과 버튼, 인풋 컴포넌트 수정
  src/components/common/Button/Button.module.css
  src/components/common/Input/Input.module.css
  src/components/common/Input/Input.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
Labels: bug

#52 feat: Add theme.css border-radius-sm size
  src/components/common/HeroCard/HeroCard.module.css
  src/components/common/Input/Input.module.css
  src/components/common/Link/Link.module.css
  src/components/common/Textarea/Textarea.module.css
  src/styles/theme.css
Labels: 수정

#53 refactor: Extract state and validation logic
  src/components/common/Input/Input.module.css
  src/components/common/Input/Input.tsx
  src/hooks/index.js
  src/hooks/useInput.ts
  src/styles/custom-base.css
  src/utils/index.js
  src/utils/validate.ts
Labels: 버그, 리팩토링, 수정

#54 [feat] Create Hero register, photo, complete page & [fix] Amend style code
  src/components/common/Button/Button.module.css
  src/components/common/HeroCard/HeroCard.tsx
  src/components/common/Input/Input.module.css
  src/components/common/Input/Input.tsx
  src/pages/register/Register.module.css
  src/pages/register/complete/Complete.module.css
  src/pages/register/complete/index.tsx
  src/pages/register/index.tsx
  src/pages/register/photo/Photo.module.css
  src/pages/register/photo/index.tsx
  src/styles/custom-base.css
  src/styles/theme.css
  src/utils/validate.ts
Labels: bug, 기능 구현

#46 [feat] Create Hero, Mission API
  src/components/common/Dialog/Dialog.tsx
  src/models/Hero.ts
  src/models/Mission.ts
  src/models/index.ts
  src/pages/api/hello.ts
  src/pages/api/hero/[id].ts
  src/pages/api/hero/index.ts
  src/pages/api/mission/[id].ts
  src/pages/api/mission/acceptance.ts
  src/pages/api/mission/completion.ts
  src/pages/api/mission/index.ts
  src/types/global.d.ts
  src/utils/client/focus-tab.ts
  src/utils/server/dbConnect.ts
  stories/Page.tsx
Labels: 현진 🐯, 기능 구현

#61 [feat] Create ToonifyAPI function
  package-lock.json
  package.json
  src/apis/index.ts
  src/apis/toonify.ts
Labels: 재영 🦄, 기능 구현

#60 feat: Create Camera component
  src/components/common/Button/Button.tsx
  src/components/common/Camera/Camera.module.css
  src/components/common/Camera/Camera.stories.tsx
  src/components/common/Camera/Camera.tsx
  src/components/common/Camera/index.js
  src/components/common/index.js
Labels: 채와와 🐵, 기능 구현

#63 [feat] Connect to toonify api
  src/apis/index.ts
  src/apis/missions.ts
  src/components/common/Button/Button.tsx
  src/components/common/HeroCard/HeroCard.module.css
  src/components/common/HeroCard/HeroCard.tsx
  src/components/common/index.js
  src/components/index.js
  src/components/pages/Board/HeroList/HeroItem.module.css
  src/components/pages/Board/HeroList/HeroItem.stories.tsx
  src/components/pages/Board/HeroList/HeroItem.tsx
  src/components/pages/Board/HeroList/HeroList.module.css
  src/components/pages/Board/HeroList/HeroList.stories.tsx
  src/components/pages/Board/HeroList/HeroList.tsx
  src/components/pages/Board/HeroList/index.js
  src/components/pages/Board/MissionCard.stories.tsx
  src/components/pages/Board/MissionCard.tsx
  src/components/pages/Board/MissionForm/MissionForm.module.css
  src/components/pages/Board/MissionForm/MissionForm.stories.tsx
  src/components/pages/Board/MissionForm/MissionForm.tsx
  src/components/pages/Board/MissionForm/index.js
  src/components/pages/Board/MissionInfo/MissionInfo.module.css
  src/components/pages/Board/MissionInfo/MissionInfo.stories.tsx
  src/components/pages/Board/MissionInfo/MissionInfo.tsx
  src/components/pages/Board/MissionInfo/index.js
  src/components/pages/Board/Result/Result.module.css
  src/components/pages/Board/Result/Result.stories.tsx
  src/components/pages/Board/Result/Result.tsx
  src/components/pages/Board/Result/index.js
  src/components/pages/Board/index.js
  src/components/pages/Register/Camera/Camera.module.css
  src/components/pages/Register/Camera/Camera.stories.tsx
  src/components/pages/Register/Camera/Camera.tsx
  src/components/pages/Register/Camera/index.js
  src/components/pages/Register/Complete/Complete.module.css
  src/components/pages/Register/Complete/Complete.tsx
  src/components/pages/Register/Complete/index.js
  src/components/pages/Register/HeroRegister/HeroRegister.module.css
  src/components/pages/Register/HeroRegister/HeroRegister.stories.tsx
  src/components/pages/Register/HeroRegister/HeroRegister.tsx
  src/components/pages/Register/HeroRegister/index.js
  src/components/pages/Register/Register.tsx
  src/components/pages/Register/index.js
  src/components/pages/index.js
  src/pages/register/complete/index.tsx
  src/pages/register/index.tsx
  src/pages/register/photo/Photo.module.css
  src/pages/register/photo/index.tsx
Labels: 채와와 🐵, 기능 구현

#65 feat: Create AuthInput, AuthForm component
  src/components/Auth/AuthForm/AuthForm.module.css
  src/components/Auth/AuthForm/AuthForm.stories.tsx
  src/components/Auth/AuthForm/AuthForm.tsx
  src/components/Auth/AuthForm/index.js
  src/components/Auth/AuthInput/AuthInput.module.css
  src/components/Auth/AuthInput/AuthInput.stories.tsx
  src/components/Auth/AuthInput/AuthInput.tsx
  src/components/Auth/AuthInput/index.js
  src/components/Auth/index.js
Labels: 기능 구현

#66 feat: Create signup page
  src/pages/signup/index.tsx
  src/pages/signup/signup.module.css
Labels: 기능 구현

#68 [feat] 이미지 서버 연동
  package-lock.json
  package.json
  src/components/pages/Board/HeroList/HeroList.tsx
  src/components/pages/Board/MissionCard.tsx
  src/components/pages/Board/Result/Result.tsx
  src/models/Hero.ts
  src/pages/api/hero/[id].ts
  src/pages/api/hero/index.ts
  src/pages/api/mission/[id].ts
  src/pages/api/mission/index.ts
  src/states/heroes.ts
  src/types/heroes.d.ts
  src/types/missions.d.ts
  src/utils/server/cloudStorage.ts
  src/utils/server/dbConnect.ts
  src/utils/server/index.ts
Labels: 재영 🦄, 기능 구현

#70 [feat] Create Herolist page
  src/components/common/Button/Button.module.css
  src/components/common/HeroCard/HeroCard.tsx
  src/components/pages/Register/Camera/Camera.module.css
  src/components/pages/Register/Camera/Camera.tsx
  src/components/pages/Register/HeroRegister/HeroRegister.module.css
  src/components/pages/Register/HeroRegister/HeroRegister.tsx
  src/components/pages/Register/Register.tsx
  src/pages/herolist/herolist.module.css
  src/pages/herolist/index.tsx
  src/pages/herolist/mockup.js
Labels: 채와와 🐵, 기능 구현, 버그

#72 fix: Add dbConnect import code
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/auth/signup.ts
Labels: bug

#73 [feat] Add spinner, [fix] Amend server code
  package-lock.json
  package.json
  src/components/pages/Register/Camera/Camera.module.css
  src/components/pages/Register/Camera/Camera.tsx
  src/components/pages/Register/HeroRegister/HeroRegister.module.css
  src/components/pages/Register/HeroRegister/HeroRegister.tsx
  src/components/pages/Register/Register.tsx
  src/pages/api/hero/index.ts
  src/pages/herolist/index.tsx
  src/pages/index.tsx
  src/styles/custom-base.css
Labels: bug, 채와와 🐵, 기능 구현

#77 Missions page jeayeong
  .storybook/main.js
  next.config.js
  package-lock.json
  package.json
  src/@types/assets.d.ts
  src/@types/events.d.ts
  src/@types/global.d.ts
  src/@types/heroes.d.ts
  src/@types/missions.d.ts
  src/@types/user.d.ts
  src/components/Missions/HeroList/HeroItem.tsx
  src/components/Missions/HeroList/HeroList.module.css
  src/components/Missions/HeroList/HeroList.tsx
  src/components/Missions/MissionCard/MissionCard.stories.tsx
  src/components/Missions/MissionCard/MissionCard.tsx
  src/components/Missions/MissionForm/MissionForm.module.css
  src/components/Missions/MissionForm/MissionForm.stories.tsx
  src/components/Missions/MissionForm/MissionForm.tsx
  src/components/Missions/MissionInfo/MissionInfo.module.css
  src/components/Missions/MissionInfo/MissionInfo.tsx
  src/components/Missions/MissionItem/MissionItem.module.css
  src/components/Missions/MissionItem/MissionItem.stories.tsx
  src/components/Missions/MissionItem/MissionItem.tsx
  src/components/Missions/Result/Result.tsx
  src/components/common/Button/Button.module.css
  src/components/common/Slide/Slide.tsx
  src/components/pages/Register/Register.tsx
  src/hooks/index.js
  src/hooks/index.ts
  src/hooks/useHeroes.ts
  src/hooks/useMissions.ts
  src/pages/api/hero/index.ts
  src/pages/api/missions/[id].ts
  src/pages/api/missions/index.ts
  src/pages/herolist/index.tsx
  src/pages/missions/index.tsx
  src/states/heroes.ts
  src/states/index.ts
  src/states/missions.ts
Labels: 재영 🦄, 기능 구현, 버그

#80 [feat] Implement PWA
  .gitignore
  next.config.js
  package-lock.json
  package.json
  public/images/icons/ logo-512x512.png
  public/images/icons/android-icon-144x144.png
  public/images/icons/android-icon-192x192.png
  public/images/icons/android-icon-36x36.png
  public/images/icons/android-icon-48x48.png
  public/images/icons/android-icon-72x72.png
  public/images/icons/android-icon-96x96.png
  public/images/icons/apple-icon-114x114.png
  public/images/icons/apple-icon-120x120.png
  public/images/icons/apple-icon-144x144.png
  public/images/icons/apple-icon-152x152.png
  public/images/icons/apple-icon-180x180.png
  public/images/icons/apple-icon-57x57.png
  public/images/icons/apple-icon-60x60.png
  public/images/icons/apple-icon-72x72.png
  public/images/icons/apple-icon-76x76.png
  public/images/icons/apple-icon-precomposed.png
  public/images/icons/apple-icon.png
  public/images/icons/favicon-16x16.png
  public/images/icons/favicon-32x32.png
  public/images/icons/favicon-96x96.png
  public/images/icons/favicon.ico
  public/images/icons/logo-192x192.png
  public/images/icons/logo-512x512.png
  public/images/icons/ms-icon-144x144.png
  public/images/icons/ms-icon-150x150.png
  public/images/icons/ms-icon-310x310.png
  public/images/icons/ms-icon-70x70.png
  public/manifest.json
  src/components/common/Dialog/Dialog.tsx
  src/pages/_document.tsx
Labels: 채와와 🐵, 기능 구현

#83 [fix] Resolve completeNumber bug
  package-lock.json
  public/sw.js
  public/sw.js.map
  public/workbox-327c579b.js
  public/workbox-327c579b.js.map
  src/components/Register/Camera/Camera.tsx
  src/components/common/HeroCard/HeroCard.module.css
  src/components/common/HeroCard/HeroCard.tsx
  src/pages/herolist/index.tsx
Labels: 재영 🦄, 버그

#86 [fix] Amend layout
  public/favicon.ico
  public/images/icons/ logo-512x512.png
  public/images/icons/android-icon-144x144.png
  public/images/icons/android-icon-192x192.png
  public/images/icons/android-icon-36x36.png
  public/images/icons/android-icon-48x48.png
  public/images/icons/android-icon-72x72.png
  public/images/icons/android-icon-96x96.png
  public/images/icons/apple-icon-114x114.png
  public/images/icons/apple-icon-120x120.png
  public/images/icons/apple-icon-144x144.png
  public/images/icons/apple-icon-152x152.png
  public/images/icons/apple-icon-180x180.png
  public/images/icons/apple-icon-57x57.png
  public/images/icons/apple-icon-60x60.png
  public/images/icons/apple-icon-72x72.png
  public/images/icons/apple-icon-76x76.png
  public/images/icons/apple-icon-precomposed.png
  public/images/icons/apple-icon.png
  public/images/icons/favicon-16x16.png
  public/images/icons/favicon-32x32.png
  public/images/icons/favicon-96x96.png
  public/images/icons/favicon.ico
  public/images/icons/logo-192x192.png
  public/images/icons/logo-512x512.png
  public/images/icons/ms-icon-144x144.png
  public/images/icons/ms-icon-150x150.png
  public/images/icons/ms-icon-310x310.png
  public/images/icons/ms-icon-70x70.png
  src/components/Register/Camera/Camera.module.css
  src/components/Register/Camera/Camera.tsx
  src/components/Register/HeroRegister/HeroRegister.module.css
  src/components/Register/HeroRegister/HeroRegister.tsx
  src/components/common/HeroCard/HeroCard.module.css
  src/pages/herolist/herolist.module.css
  src/pages/missions/Missions.module.css
Labels: 채와와 🐵, 버그, 리팩토링, 수정

#87 [feat] Create Authentication routing and Modify signout
  src/components/common/Nav/Nav.tsx
  src/hooks/useHeroes.ts
  src/hooks/useMissions.ts
  src/pages/_app.tsx
  src/pages/api/groups/[groupId]/heroes/[heroId].ts
  src/pages/api/groups/[groupId]/heroes/index.ts
  src/pages/api/groups/[groupId]/missions/[missionId].ts
  src/pages/api/groups/[groupId]/missions/index.ts
  src/pages/api/hero/[id].ts
  src/pages/api/hero/index.ts
  src/pages/api/missions/index.ts
  src/pages/api/missions/mission/index.ts
  src/pages/herolist/index.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/missions/index.tsx
  src/pages/register/index.tsx
  src/pages/signup/index.tsx
Labels: 현진 🐯, 기능 구현, 버그

#89 [fix] Modify API request in pages/signup/index.ts
  src/pages/signup/index.tsx
Labels: 현진 🐯, 수정

#91 fix: Resolve herolist page render error
  public/sw.js.map
  src/hooks/useHeroes.ts
  src/pages/herolist/index.tsx
Labels: 재영 🦄, 버그

#93 [feat] Add theme font, [fix] Camera component Error handling
  next.config.js
  package.json
  public/fonts/style.css
  src/apis/toonify.ts
  src/components/Missions/HeroList/HeroItem.module.css
  src/components/Missions/HeroList/HeroList.module.css
  src/components/Missions/MissionItem/MissionItem.module.css
  src/components/Missions/Result/Result.module.css
  src/components/Register/Camera/Camera.module.css
  src/components/Register/Camera/Camera.tsx
  src/components/Register/Complete/Complete.module.css
  src/components/Register/HeroRegister/HeroRegister.module.css
  src/components/common/Button/Button.module.css
  src/components/common/Dialog/Dialog.module.css
  src/components/common/Dialog/Dialog.tsx
  src/components/common/HeroCard/HeroCard.module.css
  src/components/common/HeroCard/HeroCard.tsx
  src/components/common/Input/Input.module.css
  src/components/common/Link/Link.module.css
  src/components/common/Nav/Nav.module.css
  src/components/common/Textarea/Textarea.module.css
  src/components/common/Title/Title.module.css
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/states/heroes.ts
  src/styles/custom-base.css
  src/styles/theme.css
Labels: bug, 채와와 🐵, 기능 구현

#96 [feat] Create PWAInstallButton component, [fix] Amend HeroCard layout
  src/components/Register/Complete/Complete.module.css
  src/components/Register/HeroRegister/HeroRegister.module.css
  src/components/Register/HeroRegister/HeroRegister.tsx
  src/components/common/HeroCard/HeroCard.module.css
  src/components/common/HeroCard/HeroCard.tsx
  src/components/common/PWAInstallButton/PWAInstallButton.module.css
  src/components/common/PWAInstallButton/PWAInstallButton.tsx
  src/components/common/PWAInstallButton/index.ts
  src/components/common/index.ts
  src/pages/herolist/herolist.module.css
  src/pages/login/index.tsx
  src/utils/client/validate.ts
Labels: 채와와 🐵, 기능 구현, 수정

#114 fix: Add Input HeroRegister description, title Regex
  src/utils/client/validate.ts
Labels: bug, 채와와 🐵

#116 [fix] Use groupId in token, instead of atom
  src/@types/user.d.ts
  src/hooks/useHeroes.ts
  src/hooks/useMissions.ts
  src/pages/api/auth/[...nextauth].ts
  src/states/index.ts
  src/states/user.ts
Labels: 현진 🐯, 기능 구현, 버그, 수정

#118 fix: reset heroList, missionList state, when logout
  src/components/common/Nav/Nav.tsx
Labels: 현진 🐯, 버그, 수정

#119 fix: Add ButtonText props to AuthForm component
  src/components/Auth/AuthForm/AuthForm.tsx
Labels: 현진 🐯, 기능 구현, 수정

#121 [fix] Network error handling - Jaeyeong
  src/apis/toonify.ts
  src/components/Missions/MissionCard/MissionCard.tsx
  src/components/Register/Camera/Camera.tsx
  src/components/Register/Register.tsx
  src/components/common/Dialog/Default/Dialog.tsx
  src/components/common/Dialog/ErrorDialog/ErrorDialog.tsx
  src/hooks/useHeroes.ts
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
Labels: 재영 🦄, 버그

#122 fix: Modify text in login, signup page
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
Labels: 현진 🐯, 수정

#123 fix: resolve type error of authorize temporarily
  src/pages/api/auth/[...nextauth].ts
Labels: 현진 🐯, 버그, 수정

#124 feat: Apply slide animation
  src/components/Register/Camera/Camera.tsx
  src/components/Register/Complete/Complete.tsx
  src/components/Register/HeroRegister/HeroRegister.tsx
  src/components/Register/Register.tsx
  src/pages/herolist/index.tsx
  src/pages/login/index.tsx
  src/pages/missions/index.tsx
  src/pages/register/index.tsx
  src/pages/signup/index.tsx
Labels: 재영 🦄, 기능 구현

#126 [feat] Add opengraph meta tag, [fix] Remove Herolist style code
  public/images/icons/ogImage.jpg
  src/components/common/PWAInstallButton/PWAInstallButton.tsx
  src/pages/_document.tsx
  src/pages/herolist/herolist.module.css
Labels: 채와와 🐵, 기능 구현, 수정

#127 feat: Add title tag in page components
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/herolist/index.tsx
  src/pages/login/index.tsx
  src/pages/missions/index.tsx
  src/pages/register/index.tsx
  src/pages/signup/index.tsx
Labels: 기능 구현
